const fs = require("fs");
const path = require("path");

const routesDir = path.join(__dirname, "routes");
const controllersDir = path.join(__dirname, "controllers");
const outputFile = path.join(__dirname, "API_SPEC.md");

const extractDocs = () => {
  let markdown = "# Zitara API Specification\n\n";
  markdown +=
    "This document is automatically generated by `generateDocs.js`. It provides a reference for all API endpoints.\n\n";

  const routeFiles = fs
    .readdirSync(routesDir)
    .filter((file) => file.endsWith(".js") && file !== "index.js");

  routeFiles.forEach((routeFile) => {
    const routeName = routeFile.replace("Routes.js", "").toUpperCase();
    markdown += `## ${routeName} Endpoints\n\n`;
    markdown +=
      "| Method | Endpoint | Description | Parameters | Auth Required |\n";
    markdown += "| :--- | :--- | :--- | :--- | :--- |\n";

    const routeContent = fs.readFileSync(
      path.join(routesDir, routeFile),
      "utf8",
    );
    const controllerFile = routeFile.replace("Routes.js", "Controller.js");
    const controllerPath = path.join(controllersDir, controllerFile);

    let controllerContent = "";
    if (fs.existsSync(controllerPath)) {
      controllerContent = fs.readFileSync(controllerPath, "utf8");
    }

    // Patterns to match router.post('/path', middleware1, middleware2, controllerMethod)
    const routeRegex =
      /router\.(get|post|put|delete)\(\s*["']([^"']+)["']\s*,\s*([\s\S]*?)\)/g;
    let match;

    while ((match = routeRegex.exec(routeContent)) !== null) {
      const method = match[1].toUpperCase();
      const endpoint = `/api/${routeName.toLowerCase()}${match[2]}`;
      const handlerStr = match[3];
      const handlers = handlerStr.split(",").map((s) => s.trim());
      const controllerMethod = handlers.pop();
      const middleware = handlers.join(", ");

      let parameters = "N/A";
      let authRequired =
        middleware.includes("auth") || middleware.includes("protect")
          ? "✅ Yes"
          : "❌ No";

      if (controllerContent) {
        // Find the function and extract req.body/params/query keys
        const funcRegex = new RegExp(
          `exports\\.${controllerMethod}\\s*=\\s*async\\s*\\(req,\\s*res\\)\\s*=>\\s*{([\\s\\S]*?)^};`,
          "m",
        );
        const funcMatch = funcRegex.exec(controllerContent);

        if (funcMatch) {
          const params = [];
          // Match destructuring: const { a, b } = req.query/body/params
          const destructuringRegex =
            /const\s*{\s*([^}]+)\s*}\s*=\s*req\.(body|params|query)/g;
          let pMatch;
          while ((pMatch = destructuringRegex.exec(funcMatch[1])) !== null) {
            params.push(
              ...pMatch[1].split(",").map((s) => s.trim().split(":")[0].trim()),
            );
          }
          // Match direct access: req.query.page
          const directAccessRegex = /req\.(body|params|query)\.([\w]+)/g;
          while ((pMatch = directAccessRegex.exec(funcMatch[1])) !== null) {
            params.push(pMatch[2]);
          }

          if (params.length > 0) {
            parameters = `\`${[...new Set(params)].join(", ")}\``;
          }
        }
      }

      markdown += `| ${method} | \`${endpoint}\` | ${controllerMethod} | ${parameters} | ${authRequired} |\n`;
    }
    markdown += "\n";
  });

  fs.writeFileSync(outputFile, markdown);
  console.log("✅ Success: API_SPEC.md has been generated!");
};

extractDocs();
