const fs = require("fs");
const path = require("path");

const routesDir = path.join(__dirname, "routes");
const controllersDir = path.join(__dirname, "controllers");
const outputFile = path.join(__dirname, "API_SPEC.md");

const extractDocs = () => {
  let markdown = "# Zitara API Specification\n\n";
  markdown +=
    "This document is automatically generated by `generateDocs.js`. It provides a reference for all API endpoints.\n\n";

  const routeFiles = fs
    .readdirSync(routesDir)
    .filter((file) => file.endsWith(".js") && file !== "index.js");

  routeFiles.forEach((routeFile) => {
    const routeName = routeFile.replace("Routes.js", "").toUpperCase();
    markdown += `## ${routeName} Endpoints\n\n`;
    markdown +=
      "| Method | Endpoint | Description | Parameters | Auth Required |\n";
    markdown += "| :--- | :--- | :--- | :--- | :--- |\n";

    const routeContent = fs.readFileSync(
      path.join(routesDir, routeFile),
      "utf8",
    );
    const controllerFile = routeFile.replace("Routes.js", "Controller.js");
    const controllerPath = path.join(controllersDir, controllerFile);

    let controllerContent = "";
    if (fs.existsSync(controllerPath)) {
      controllerContent = fs.readFileSync(controllerPath, "utf8");
    }

    // Patterns to match router.post('/path', middleware, controllerMethod)
    const routeRegex =
      /router\.(get|post|put|delete)\(\s*["']([^"']+)["']\s*,\s*(?:([^,]+),)?\s*([^)]+)\)/g;
    let match;

    while ((match = routeRegex.exec(routeContent)) !== null) {
      const method = match[1].toUpperCase();
      const endpoint = `/api/${routeName.toLowerCase()}${match[2]}`;
      const middleware = match[3] ? match[3].trim() : "";
      const controllerMethod = match[4].trim();

      let parameters = "N/A";
      let authRequired =
        middleware.includes("auth") || middleware.includes("protect")
          ? "✅ Yes"
          : "❌ No";

      if (controllerContent) {
        // Try to find the function in the controller and extract req.body/params
        const funcRegex = new RegExp(
          `exports\\.${controllerMethod}\\s*=\\s*async\\s*\\(req,\\s*res\\)\\s*=>\\s*{([\\s\\S]*?)^};`,
          "m",
        );
        const funcMatch = funcRegex.exec(controllerContent);

        if (funcMatch) {
          const bodyMatch =
            /const\\s*{\\s*([^}]+)\\s*}\\s*=\\s*req\\.(body|params|query)/.exec(
              funcMatch[1],
            );
          if (bodyMatch) {
            parameters = `\`${bodyMatch[1].trim()}\``;
          }
        }
      }

      markdown += `| ${method} | \`${endpoint}\` | ${controllerMethod} | ${parameters} | ${authRequired} |\n`;
    }
    markdown += "\n";
  });

  fs.writeFileSync(outputFile, markdown);
  console.log("✅ Success: API_SPEC.md has been generated!");
};

extractDocs();
